/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    ExamQuery: typeof import('./src/components/ExamQuery.vue')['default']
    ExamSchedule: typeof import('./src/components/ExamSchedule.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NGradientText: typeof import('naive-ui')['NGradientText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    ThemeSettings: typeof import('./src/components/ThemeSettings.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
